In [ ]:
import torch

class NeuralNetwork(torch.nn.Module):
    def __init__(self, num_inputs, num_outputs): #1
        super().__init__()
        self.layers = torch.nn.Sequential(
            # 1st hidden layer
            torch.nn.Linear(num_inputs, 30), #2
            torch.nn.ReLU(), #3
            
            # 2nd hidden layer
            torch.nn.Linear(30, 20), #4
            torch.nn.ReLU(),
            
            # output layer
            torch.nn.Linear(20, num_outputs),
        )
    
    def forward(self, x):
        logits = self.layers(x)
        return logits #5

In [3]:
model = NeuralNetwork(50, 3)

In [4]:
print(model)

NeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=50, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
  )
)


In [5]:
num_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print("Total number of trainable model parameters:", num_params)

Total number of trainable model parameters: 2213


In [6]:
print(model.layers[0].weight)

Parameter containing:
tensor([[ 0.0352, -0.0646,  0.1339,  ..., -0.1146, -0.0144,  0.0986],
        [ 0.1345, -0.0952, -0.1130,  ...,  0.0334,  0.0009, -0.0584],
        [-0.1130, -0.0883,  0.0138,  ..., -0.0738, -0.0492, -0.0671],
        ...,
        [-0.0442,  0.0783,  0.0945,  ..., -0.0532,  0.0977,  0.0411],
        [-0.0906, -0.1345, -0.0413,  ...,  0.0253, -0.0618,  0.1165],
        [ 0.1308,  0.0639, -0.0554,  ...,  0.0703, -0.0825,  0.0697]],
       requires_grad=True)


In [7]:
print(model.layers[0].weight.shape)

torch.Size([30, 50])


In [8]:
print(model.layers[0].bias.shape)

torch.Size([30])


In [ ]:
torch.manual_seed(123)

model = NeuralNetwork(50, 3)
print(model.layers[0].weight)

Parameter containing:
tensor([[-0.0577,  0.0047, -0.0702,  ...,  0.0222,  0.1260,  0.0865],
        [ 0.0502,  0.0307,  0.0333,  ...,  0.0951,  0.1134, -0.0297],
        [ 0.1077, -0.1108,  0.0122,  ...,  0.0108, -0.1049, -0.1063],
        ...,
        [-0.0787,  0.1259,  0.0803,  ...,  0.1218,  0.1303, -0.1351],
        [ 0.1359,  0.0175, -0.0673,  ...,  0.0674,  0.0676,  0.1058],
        [ 0.0790,  0.1343, -0.0293,  ...,  0.0344, -0.0971, -0.0509]],
       requires_grad=True)


In [15]:
torch.manual_seed(123)

X = torch.rand((1, 50))
out = model(X)
print(out)

tensor([[-0.1262,  0.1080, -0.1792]], grad_fn=<AddmmBackward0>)


In [17]:
with torch.no_grad():
    out = model(X)
print(out)

tensor([[-0.1262,  0.1080, -0.1792]])


In [18]:
with torch.no_grad():
    out = torch.softmax(model(X), dim=1)
print(out)

tensor([[0.3113, 0.3934, 0.2952]])
