In [2]:
import torch
torch.__version__

'2.4.0+cu121'

In [3]:
torch.cuda.is_available()

True

In [4]:
import torch
tensor0d = torch.tensor(1)
tensor0d

tensor(1)

In [5]:
tensor3d = torch.tensor([[[1, 2], [3, 4]],[[5, 6], [7, 8]]])
tensor3d

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [6]:
tensor1d = torch.tensor([1, 2, 3])
print(tensor1d.dtype)

torch.int64


In [7]:
floatvec = torch.tensor([1.0, 2.0, 3.0])
print(floatvec.dtype)

torch.float32


In [8]:
floatvec = tensor1d.to(torch.float32)
print(floatvec.dtype)

torch.float32


In [9]:
tensor2d = torch.tensor([[1, 2, 3],
[4, 5, 6]])
print(tensor2d)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [10]:
print(tensor2d.shape)

torch.Size([2, 3])


In [11]:
print(tensor2d.reshape(3, 2))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [12]:
print(tensor2d.view(3, 2))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [13]:
print(tensor2d)
print(tensor2d.T)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [14]:
print(tensor2d.matmul(tensor2d.T))

tensor([[14, 32],
        [32, 77]])


In [15]:
print(tensor2d @ tensor2d.T)

tensor([[14, 32],
        [32, 77]])


In [ ]:
import torch.nn.functional as F #1

y = torch.tensor([1.0]) #2
x1 = torch.tensor([1.1]) #3
w1 = torch.tensor([2.2]) #4
b = torch.tensor([0.0]) #5

z = x1 * w1 + b #6
a = torch.sigmoid(z) #7

loss = F.binary_cross_entropy(a, y)

In [19]:
from torch.autograd import grad


grad_L_w1 = grad(loss, w1, retain_graph=True) #1
grad_L_b = grad(loss, b, retain_graph=True)

In [ ]:
print(grad_L_w1)
print(grad_L_b)

(tensor([-0.0898]),)
(tensor([-0.0817]),)


In [21]:
loss.backward()
print(w1.grad)
print(b.grad)

tensor([-0.0898])
tensor([-0.0817])
